platform :ios, '9.0'
use_frameworks!



target 'Youtube' do



#pod "youtube-ios-player-helper", "~> 0.1.1"
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'
pod 'YouTubePlayer'
pod 'Alamofire', '~> 4.5'


end
